main: cn.wode490390.nukkit.flyingsquid.FlyingSquidPlugin
name: "FlyingSquid"
description: "Flying squid plugin for Nukkit"
author: "wode490390"
website: "http://wode490390.cn/"
version: "${pom.version}"
api: ["1.0.0"]
load: POSTWORLD
